spring:
  rabbitmq:
    host: 192.168.200.119 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: hmall # 密码
    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: true # 开启publisher return机制
logging:
  level:
    com.itheima.publisher: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS